name: .NET CI/CD with Code Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

   
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./**/coverage.cobertura.xml
